custom:
  - "https://github.com/bor-project/amneziageo#support"
# github: [bor-project]        # enable if you turn on GitHub Sponsors
# buy_me_a_coffee: <username>   # enable if you create a Buy Me a Coffee account (fiat)
